### ISSUE TITLE
Could not log "sql.active_record" event.

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/draft_log#11]
In https://ide.c9.io/wamelias/msm-debug, visiting  a [director's show page](https://msm-debug-wamelias.c9users.io/directors/1) results in:

```
Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 2, expected 1) ["/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/log_subscriber.rb:45:in `type_casted_binds'", "/usr/local/rvm/gems/ruby-2.3.4/bundler/gems/draft_log-e37849266cfd/lib/draft_log/active_record_log_subscriber.rb:21:in `sql'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/subscriber.rb:99:in `finish'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/log_subscriber.rb:83:in `finish'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/notifications/fanout.rb:102:in `finish'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/notifications/fanout.rb:46:in `block in finish'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/notifications/fanout.rb:46:in `each'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/notifications/fanout.rb:46:in `finish'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:27:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/sqlite3_adapter.rb:208:in `exec_query'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:375:in `select_prepared'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:40:in `select_all'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `block in select_all'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'", "/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:104:in `cache_sql'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/querying.rb:39:in `find_by_sql'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/statement_cache.rb:107:in `execute'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/core.rb:187:in `find'", "/home/ubuntu/workspace/app/controllers/directors_controller.rb:9:in `show'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:186:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:30:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:131:in `run_callbacks'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_controller/metal/rescue.rb:20:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/railties/controller_runtime.rb:22:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:124:in `process'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionview-5.1.6/lib/action_view/rendering.rb:30:in `process'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_controller/metal.rb:189:in `dispatch'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_controller/metal.rb:253:in `dispatch'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:31:in `serve'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:50:in `block in serve'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `each'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `serve'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:844:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/meta_request-0.6.0/lib/meta_request/middlewares/app_request_handler.rb:13:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/meta_request-0.6.0/lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'", "/usr/local/rvm/gems/ruby-2.3.4/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/rack-2.0.5/lib/rack/conditional_get.rb:25:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'", "/usr/local/rvm/gems/ruby-2.3.4/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/cookies.rb:613:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activerecord-5.1.6/lib/active_record/migration.rb:556:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:97:in `run_callbacks'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:24:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/bundler/gems/dev_toolbar-f9745615dc92/lib/dev_toolbar/middleware.rb:10:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:59:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/rack-contrib-2.0.1/lib/rack/contrib/response_headers.rb:17:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/meta_request-0.6.0/lib/meta_request/middlewares/headers.rb:16:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/web-console-3.6.2/lib/web_console/middleware.rb:135:in `call_app'", "/usr/local/rvm/gems/ruby-2.3.4/gems/web-console-3.6.2/lib/web_console/middleware.rb:22:in `block in call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/web-console-3.6.2/lib/web_console/middleware.rb:20:in `catch'", "/usr/local/rvm/gems/ruby-2.3.4/gems/web-console-3.6.2/lib/web_console/middleware.rb:20:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.1.6/lib/rails/rack/logger.rb:36:in `call_app'", "/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `block in call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `tagged'", "/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.6/lib/action_dispatch/middleware/static.rb:125:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'", "/usr/local/rvm/gems/ruby-2.3.4/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'", "/usr/local/rvm/gems/ruby-2.3.4/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'", "/usr/local/rvm/gems/ruby-2.3.4/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'", "/usr/local/rvm/gems/ruby-2.3.4/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'"]

We received a request at 09:20PM on Friday, May 11! Someone wants to
  GET /directors/1

The route told me to use the "DirectorsController" and "show" action.

I found these inputs in flexible path segments:
{
    :id_to_display => "1"
}

The final params hash containing all inputs looks like this:
  # params
{
    "id_to_display" => "1"
}

The "DirectorsController#show" action defined these instance variables:
{
    "@director" => "#<Director:0x007fdd650c7d90>"
}

The "DirectorsController#show" action told me to use
  "app/views/director_templates/show_details.html.erb"
to format the response.

Completed 200 OK in 264ms (Views: 228.4ms | ActiveRecord: 2.5ms)

========================================
```

Any ideas?

**Comment by murugan-r** [comment]
@raghubetina Need write access to the above c9 instance.

**Comment by murugan-r** [comment]
The error is due to different rails version. Can we lock the `draft_log` gem to be used in Rails <=5.1.4 .

**Comment by arjunvenkat** [comment]
Hi Murugan, looks like we need to stay above Rails version 5.1.4 for some future projects, can we figure this out without capping the rails version to 5.1.4?

**Comment by raghubetina** [comment]
@murugan-r This is high priority — in MSM Associations, the extra log output is causing the characters#index action to freeze Cloud9 workspaces.

We're going to be upgrading all projects to 5.2 next quarter anyway, so we need to sort this out.

**Comment by murugan-r** [comment]
@raghubetina @arjunvenkat Fixed the issue.
